name: "Hariane 2 MQTT"
description: "Extracts Hariane  water data into MQTT a.o."
version: 0.2.2
slug: "hariane_2_mqtt"
url: https://github.com/Dim145/Hariane2Mqtt
init: true
homeassistant_api: true
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - addon_configs:rw
services:
  - mqtt:need
options:
  log_level: info
  debug: true
  cron: "0 * * * *"
  hariane_num_contrat: ""
  hariane_password: ""
  hariane_username: ""
  mqtt_client_id: harianne2mqtt_client
  mqtt_host: ""
  mqtt_password: ""
  mqtt_port: 1883
  mqtt_topic: homeassistant
  mqtt_username: ""
  calculate_total_consumption: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  debug: bool?
  cron: str?
  hariane_password: password?
  hariane_username: str?
  hariane_num_contrat: str?
  mqtt_host: str?
  mqtt_port: port?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_client_id: str?
  mqtt_topic: str?
  calculate_total_consumption: bool?
    
